use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{spanned::Spanned, FnArg, ImplItemFn, ReturnType};

use super::ImplFns;

pub(crate) fn inline_constructor(
    output: &mut ImplFns,
    mut f: ImplItemFn,
) -> Result<(), TokenStream> {
    let fn_ident = f.sig.ident.clone();

    // Create the new uninit constructor
    let syn::ImplItemFn {
        attrs,
        vis,
        defaultness: _,
        sig: _,
        block: _,
    } = &f;

    let uninit = uninit_constructor(&fn_ident, attrs, vis);
    output.emplacing_constructors.push(uninit.into());

    // Get the last expr in the function body
    let expr = match f.block.stmts.last_mut() {
        Some(syn::Stmt::Expr(expr, _)) => expr,
        Some(stmt) => return Err(quote::quote_spanned! { stmt.span() =>
            compile_error!("[E0006, spati] invalid constructor body: functions marked `#[super]` have to end with a constructor"),
        }.into()),
        None => return Err(quote::quote_spanned! { f.block.span() =>
            compile_error!("[E0005, spati] empty constructor body: functions marked `#[super]` cannot be empty"),
        }.into()),
    };

    // Rewrite the last expr in the function body
    let syn::Expr::Struct(strukt) = expr else {
        return Err(quote::quote_spanned! { expr.span() =>
            compile_error!("[E0006, spati] invalid constructor body: expected a struct expression as the last statement"),
        }.into());
    };
    *expr = inline_new_init(strukt);

    // Rewrite the existing constructors signature to emplace
    f.sig.ident = format_ident!("spati_init_{}", fn_ident);
    f.sig.output = ReturnType::Default;
    let inputs = f.sig.inputs.clone();
    f.sig.inputs.clear();
    f.sig
        .inputs
        .push(FnArg::Receiver(syn::parse2(quote! { &mut self }).unwrap()));
    f.sig.inputs.extend(inputs);

    output.emplacing_constructors.push(f.into());
    Ok(())
}

fn uninit_constructor(
    fn_ident: &syn::Ident,
    attrs: &[syn::Attribute],
    vis: &syn::Visibility,
) -> ImplItemFn {
    let uninit_ident = format_ident!("spati_uninit_{}", fn_ident);
    let uninit: syn::ImplItemFn = syn::parse2(quote! {
        #(#attrs)*
        /// # Safety
        ///
        /// This method has been generated by the `spati` crate.
        /// It must be called using the `spati` constructor macro.
        #vis unsafe fn #uninit_ident() -> Self
        {
            Self { inner: ::core::mem::MaybeUninit::uninit() }
        }
    })
    .unwrap();
    uninit
}

/// Convert `Self { .. }` to writes into a `MaybeUninit<Self>`
pub(crate) fn inline_new_init(strukt: &mut syn::ExprStruct) -> syn::Expr {
    let assignments = strukt
        .fields
        .iter()
        .map(|field| {
            let key = &field.member;
            let expr = &field.expr;
            syn::parse2(quote! {{
                unsafe { (&raw mut (*_this).#key).write(#expr) };
            }})
            .unwrap()
        })
        .collect::<Vec<syn::Block>>();

    syn::parse2(quote! {{
        let _this = self.inner.as_mut_ptr();
        #(#assignments)*
    }})
    .unwrap()
}
