use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{spanned::Spanned, FnArg, ImplItemFn, ReturnType};

use crate::utils::{self, expr_path_ident, path_ident};

use super::ImplFns;

mod inline;
mod pointer;

/// Rewrite a `#[super]` statement to create the inner type instead
pub(crate) fn rewrite_super_constructor(
    output: &mut ImplFns,
    mut f: ImplItemFn,
    ident: &syn::Ident,
) -> Result<(), TokenStream> {
    let fn_ident = f.sig.ident.clone();

    // Create the new uninit constructor
    let syn::ImplItemFn {
        attrs,
        vis,
        defaultness: _,
        sig,
        block: _,
    } = &f;

    match utils::constructor_type(sig, ident) {
        utils::ConstructorKind::Inline => todo!(),
        utils::ConstructorKind::Pointer => todo!(),
        utils::ConstructorKind::Other => {
            return Err(quote::quote_spanned! { sig.output.span() =>
                compile_error!("[E0009, spati] invalid constructor return type"),
            }
            .into())
        }
    }

    let uninit_ident = format_ident!("spati_uninit_{}", fn_ident);
    let uninit: syn::ImplItemFn = syn::parse2(quote! {
        #(#attrs)*
        /// # Safety
        ///
        /// This method has been generated by the `spati` crate.
        /// It must be called using the `spati` constructor macro.
        #vis unsafe fn #uninit_ident() -> Self
        {
            Self { inner: ::core::mem::MaybeUninit::uninit() }
        }
    })
    .unwrap();
    output.emplacing_constructors.push(uninit.into());

    // Get the last expr in the function body
    let expr = match f.block.stmts.last_mut() {
        Some(syn::Stmt::Expr(expr, _)) => expr,
        Some(stmt) => return Err(quote::quote_spanned! { stmt.span() =>
            compile_error!("[E0006, spati] invalid constructor body: functions marked `#[super]` have to end with a constructor"),
        }.into()),
        None => return Err(quote::quote_spanned! { f.block.span() =>
            compile_error!("[E0005, spati] empty constructor body: functions marked `#[super]` cannot be empty"),
        }.into()),
    };

    // Rewrite the last expr in the function body
    match expr {
        // e.g. `Self { .. }`
        syn::Expr::Struct(strukt) => *expr = inline::inline_new_init(strukt),
        // e.g. `Box::new(Self { .. })`
        syn::Expr::Call(call) => *expr = pointer::pointer_new_init(call)?,
        expr => return Err(quote::quote_spanned! { expr.span() =>
            compile_error!("[E0006, spati] invalid constructor body: functions marked `#[super]` have to end with a struct expression"),
        }.into()),
    }

    // Rewrite the existing constructors signature to emplace
    f.sig.ident = format_ident!("spati_init_{}", fn_ident);
    f.sig.output = ReturnType::Default;
    let inputs = f.sig.inputs.clone();
    f.sig.inputs.clear();
    f.sig
        .inputs
        .push(FnArg::Receiver(syn::parse2(quote! { &mut self }).unwrap()));
    f.sig.inputs.extend(inputs);

    output.emplacing_constructors.push(f.into());
    Ok(())
}
