use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{spanned::Spanned, ImplItemFn, Signature};

use super::ImplFns;
use crate::utils::{expr_path_ident, PointerKind};

pub(crate) fn pointer_constructor(
    output: &mut ImplFns,
    f: ImplItemFn,
    kind: PointerKind,
) -> Result<(), TokenStream> {
    let fn_ident = f.sig.ident.clone();

    // Create the new uninit constructor
    let syn::ImplItemFn {
        attrs,
        vis,
        defaultness: _,
        sig,
        mut block,
    } = f;

    // Construct the uninit function
    let uninit = uninit_constructor(&fn_ident, &attrs, &vis, kind);
    output.emplacing_constructors.push(uninit.into());

    // Get the last expr in the function body
    let expr = match block.stmts.last_mut() {
        Some(syn::Stmt::Expr(expr, _)) => expr,
        Some(stmt) => return Err(quote::quote_spanned! { stmt.span() =>
            compile_error!("[E0006, placing] invalid constructor body: functions marked `#[placing]` have to end with a constructor"),
        }.into()),
        None => return Err(quote::quote_spanned! { block.span() =>
            compile_error!("[E0005, placing] empty constructor body: functions marked `#[placing]` cannot be empty"),
        }.into()),
    };

    // Rewrite the last expr in the function body
    let syn::Expr::Call(call) = expr else {
        return Err(quote::quote_spanned! { expr.span() =>
            compile_error!("[E0006, placing] invalid constructor body: expected a call expression as the last statement"),
        }.into());
    };
    *expr = pointer_new_init(call)?;
    let constructor = init_constructor(fn_ident, sig, attrs, vis, block);
    output.emplacing_constructors.push(constructor.into());

    Ok(())
}

fn init_constructor(
    fn_ident: syn::Ident,
    sig: Signature,
    attrs: Vec<syn::Attribute>,
    vis: syn::Visibility,
    block: syn::Block,
) -> ImplItemFn {
    // Rewrite the existing constructors signature to emplace
    let init_ident = format_ident!("placing_init_{}", fn_ident);
    let inputs = sig.inputs.iter();
    let statements = &block.stmts;

    let init: syn::ImplItemFn = syn::parse2(quote! {
        #(#attrs)*
        /// # Safety
        ///
        /// This method has been generated by the `placing` crate.
        /// It must be called using the `placing` constructor macro.
        #vis unsafe fn #init_ident(self: &mut Box<Self>, #(#inputs,)*)
        {
            #(#statements)*
        }
    })
    .unwrap();
    init
}

fn uninit_constructor(
    fn_ident: &syn::Ident,
    attrs: &[syn::Attribute],
    vis: &syn::Visibility,
    _kind: PointerKind,
) -> ImplItemFn {
    let uninit_ident = format_ident!("placing_uninit_{}", fn_ident);

    let uninit: syn::ImplItemFn = syn::parse2(quote! {
        #(#attrs)*
        /// # Safety
        ///
        /// This method has been generated by the `placing` crate.
        /// It must be called using the `placing` constructor macro.
        #vis unsafe fn #uninit_ident() -> Box<Self>
        {
            Box::new(Self { inner: ::core::mem::MaybeUninit::uninit() })
        }
    })
    .unwrap();
    uninit
}

/// Convert `Box::new(Self { .. })` to writes into a `Box<MaybeUninit<Self>>`
pub(crate) fn pointer_new_init(call: &mut syn::ExprCall) -> Result<syn::Expr, TokenStream> {
    let syn::Expr::Path(path) = &*call.func else {
        return Err(quote::quote_spanned! { call.span() =>
            compile_error!("[E0006, placing] invalid constructor body: functions marked `#[placing]` can only end with a fixed set of expressions"),
        }.into());
    };

    match expr_path_ident(path).as_str() {
        "Box :: new" => {}
        _ => {
            return Err(quote::quote_spanned! { call.span() =>
                compile_error!("[E0008, placing] invalid pointer constructor"),
            }
            .into())
        }
    }

    let strukt = match call.args.first() {
        Some(syn::Expr::Struct(expr)) => expr,
        _ => {
            return Err(quote::quote_spanned! { call.span() =>
                compile_error!("[E0008, placing] invalid pointer constructor`"),
            }
            .into())
        }
    };

    let assignments = strukt
        .fields
        .iter()
        .map(|field| {
            let key = &field.member;
            let expr = &field.expr;
            syn::parse2(quote! {{
                unsafe { (&raw mut (*_this).#key).write(#expr) };
            }})
            .unwrap()
        })
        .collect::<Vec<syn::Block>>();

    Ok(syn::parse2(quote! {{
        let _this = self.inner.as_mut_ptr();
        #(#assignments)*
    }})
    .unwrap())
}
