[package]
name = "placing"
version = "1.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/placing"
documentation = "https://docs.rs/placing"
description = "A prototype notation for referentially stable constructors"
readme = "README.md"
edition = "2021"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <rust@yosh.is>"
]

[lib]
proc-macro = true 

[features]

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = { version = "2.0.91", features = ["extra-traits", "full"] }

[dev-dependencies]
trybuild = "1.0.101"
