use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{spanned::Spanned, FnArg, ImplItemFn, ReturnType};

use super::ImplFns;

/// Rewrite a `#[super]` statement to create the inner type instead
pub(crate) fn rewrite_super_constructor(
    output: &mut ImplFns,
    mut f: ImplItemFn,
) -> Result<(), TokenStream> {
    let fn_ident = f.sig.ident.clone();

    // Create the new uninit constructor
    let syn::ImplItemFn {
        attrs,
        vis,
        defaultness: _,
        sig: _,
        block: _,
    } = &f;
    let uninit_ident = format_ident!("spati_uninit_{}", fn_ident);
    let uninit: syn::ImplItemFn = syn::parse2(quote! {
        #(#attrs)*
        /// # Safety
        ///
        /// This method has been generated by the `spati` crate.
        /// It must be called using the `spati` constructor macro.
        #vis unsafe fn #uninit_ident() -> Self
        {
            Self { inner: ::core::mem::MaybeUninit::uninit() }
        }
    })
    .unwrap();
    output.emplacing_constructors.push(uninit.into());

    // Rewrite the existing constructors body to emplace
    match f.block.stmts.last_mut() {
        Some(syn::Stmt::Expr(expr, _)) => {
            match expr {
                syn::Expr::Struct(strukt) => *expr = rewrite_struct_expr(strukt),
                expr => return Err(quote::quote_spanned! { expr.span() =>
                    compile_error!("[E0006, spati] invalid constructor body: functions marked `#[super]` have to end with a struct expression"),
                }.into()),
            }
        }
        // Some(syn::Stmt::Expr(syn::Expr::Call(expr_call), _)) => {}
        Some(stmt) => return Err(quote::quote_spanned! { stmt.span() =>
            compile_error!("[E0006, spati] invalid constructor body: functions marked `#[super]` have to end with a struct expression"),
        }.into()),
        None => return Err(quote::quote_spanned! { f.block.span() =>
            compile_error!("[E0005, spati] empty constructor body: functions marked `#[super]` cannot be empty"),
        }.into()),

    };

    // Rewrite the existing constructors signature to emplace
    f.sig.ident = format_ident!("spati_init_{}", fn_ident);
    f.sig.output = ReturnType::Default;
    let inputs = f.sig.inputs.clone();
    f.sig.inputs.clear();
    f.sig
        .inputs
        .push(FnArg::Receiver(syn::parse2(quote! { &mut self }).unwrap()));
    f.sig.inputs.extend(inputs);

    output.emplacing_constructors.push(f.into());
    Ok(())
}

fn rewrite_struct_expr(strukt: &mut syn::ExprStruct) -> syn::Expr {
    let assignments = strukt
        .fields
        .iter()
        .map(|field| {
            let key = &field.member;
            let expr = &field.expr;
            syn::parse2(quote! {{
                unsafe { (&raw mut (*_this).#key).write(#expr) };
            }})
            .unwrap()
        })
        .collect::<Vec<syn::Block>>();
    syn::parse2(quote! {{
        let _this = self.inner.as_mut_ptr();
        #(#assignments)*
    }})
    .unwrap()
}
